source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8", ">= 7.0.8.3"

# レスポンスJSONを制御する
gem "active_model_serializers"

# 環境毎の設定管理を行う
gem "config"

# ユーザー認証を提供する
gem "devise"

# devise を日本語化する
gem "devise-i18n"

# ユーザーのトークン認証を提供する
gem "devise_token_auth"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

 # cors設定を管理する
 gem "rack-cors"

# メッセージを日本語化
gem "rails-i18n"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # pry コンソールを使えるようにする。
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  # テストフレームワーク rspec を導入する
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  # rubocop を使えるようにする。
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"

end

gem 'mini_magick'
gem 'image_processing', '~> 1.2'

gem "aws-sdk-s3", require: false
