# テスト(rspec)、コードルール(rubocop, eslint, prettier)のチェックを行う
name: Continuous Integration

on:
  push:
    branches-ignore:
      - "main"
  workflow_call:

jobs:
  # 処理① eslint(& prettier) のルール違反がないことをチェック
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.4.0'

      - name: Install packages
        run: npm install

      - name: Run lint
        run: npm run lint

  # 処理② jest 単体テストの実施
  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.4.0'
      
      - name: Install packages
        run: npm install

      # テスト用の環境変数を設定
      - name: Set environment variables for Supabase
        run: echo "Setting environment variables"
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_API_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_API_KEY }}
      
      - name: Run Jest tests
        run: npm run test:watch